Feat/interactions
PedroRossa/XRUI_Elements pull request #4
Opened 2020-11-03 13:45 UTC by GMoreira-Tro

2020-11-03 15:17 UTC, PedroRossa requested changes
Alem dos comentários.
Adicionar summary em todas as classes que não tem ainda e que foram mexidas aqui neste PR

2020-11-03 15:17 UTC, PedroRossa commented on Assets/InputManager/DemoScene/ExemploInputHandlers.cs
> +public class ExemploInputHandlers : MonoBehaviour
Usar nome de classes em Ingles

2020-11-03 15:17 UTC, PedroRossa commented on Assets/InputManager/DemoScene/ExemploInputHandlers.cs
> +    public InputManager.AxisHandler2D secundaryAxisHandler = null;
secondaryAxisHandler

2020-11-03 15:17 UTC, PedroRossa commented on Assets/InputManager/DemoScene/ExemploInputHandlers.cs
> +        secundaryAxisHandler.OnValueChange += PrintSecundaryAxis;
PrintSecondaryAxis

2020-11-03 15:17 UTC, PedroRossa commented on Assets/InputManager/DemoScene/ExemploInputHandlers.cs
> +    private void PrintSecundaryAxis(XRController controller, Vector2 value)
Change to PrintSecondaryAxis

2020-11-03 15:17 UTC, PedroRossa commented on Assets/InputManager/Scripts/HandlesSCripts/Axis2DType.cs
> +        Secundary2DAxis
Secondary2DAxis

2020-11-03 15:17 UTC, PedroRossa commented on Assets/InputManager/Scripts/HandlesSCripts/AxisHandler.cs
> +        }
Não pode ser deletado isso? Ou tem um uso futuro?

2020-11-03 15:17 UTC, PedroRossa commented on Assets/InputManager/Scripts/HandlesSCripts/AxisHandler2D.cs
> +        }
Pode ser deletado ou será utilizado no futuro?

2020-11-03 15:17 UTC, PedroRossa commented on Assets/InputManager/Scripts/HandlesSCripts/InputHandler.cs
> +}
Pode ser uma classe abstrata sem construtor de HandleState;
Ou existem casos que alguma classe herda de InputHandler e não precisa implementar HandleState?

2020-11-03 15:17 UTC, PedroRossa commented on Assets/InputManager/Scripts/HandlesSCripts/InputManager.cs
> +            controller = GetComponent<XRController>();
se sempre tem um controller então da pra colocar em cima da classe o [RequireComponent(typeof(XRController))] assim evita de quebrar caso o usuario esqueça de ter esse script attached no lugar que ele for usar o inputManager

2020-11-03 15:17 UTC, PedroRossa commented on Assets/Interactions/Scripts/ChangeColor.cs
> +/// </summary>
???

2020-11-03 15:17 UTC, PedroRossa commented on Assets/Interactions/Scripts/ChangeColor.cs
> +        rendererMaterial = GetComponent<MeshRenderer>().material;
Pra nao precisar dar dois "GetComponent" aqui, pega o rendererMaterial antes e depois só faz um "rendererMaterial.color" pra pegar o valor do initialcolor.

2020-11-03 15:17 UTC, PedroRossa commented on Assets/Interactions/Scripts/ChangeColor.cs
> +            return;*/
ta repetido embaixo, creio que pode ser deletado:?

2020-11-03 15:17 UTC, PedroRossa commented on Assets/Interactions/Scripts/ChangeColor.cs
> +        int rnd;
o que é rnd? colocar um nome que fique mais explicito o que quer dizer esta variável

2020-11-03 15:17 UTC, PedroRossa commented on Assets/Interactions/Scripts/ChangeColor.cs
> +    }
Qual o objetivo desta função?
Acredito que podemos ver uma formato mais simples de executar esta randomização de cores.

2020-11-03 15:17 UTC, PedroRossa commented on Assets/Interactions/Scripts/DisableWalkOnCollision.cs
> +        grabInteractor = gameObject.GetComponentInParent<XRBaseInteractor>();
Adicionar um aviso de erro caso não haja um XRBaseInteractor no parent.

2020-11-03 15:17 UTC, PedroRossa commented on Assets/Interactions/Scripts/EnableWalkOnDecolision.cs
> +        walk.enabled = true;
Importante chegar se walk não é nulo

2020-11-03 15:17 UTC, PedroRossa commented on Assets/Interactions/Scripts/Flags.cs
> +}
O que seria esta classe?

2020-11-03 15:17 UTC, PedroRossa commented on Assets/Interactions/Scripts/HandInteractionsManager.cs
> +            Destroy(gameObject.GetComponent<XRInteractorLineVisual>());
pode acontecer de não ter um LineVisual, então seria bom chegar se ele eixste antes pra não estourar erro aqui.

2020-11-03 15:17 UTC, PedroRossa commented on Assets/Interactions/Scripts/HandInteractionsManager.cs
> +                case nextFrameCommands.addRay:
Adicionar o case default:

2020-11-03 15:17 UTC, PedroRossa commented on Assets/Interactions/Scripts/HandInteractionsManager.cs
> +    private void eventConfiguration()
Primeira letra maiúscula = EventConfiguration()

2020-11-03 15:17 UTC, PedroRossa commented on Assets/Interactions/Scripts/HandInteractionsManager.cs
> +    private void addRay()
AddRay()

2020-11-03 15:17 UTC, PedroRossa commented on Assets/Interactions/Scripts/HandInteractionsManager.cs
> +    private void addDirect()
AddDirect()

2020-11-03 15:17 UTC, PedroRossa commented on Assets/Interactions/Scripts/MoveWithJoystick.cs
> +        grabInteractable = GetComponent<XRGrabInteractable>();
se é obrigatorio ter XRGrabInteractable, adicionar
RequireComponent[typeof(XRGrabInteractable)]

2020-11-03 15:17 UTC, PedroRossa commented on Assets/Interactions/Scripts/RealocateToScene.cs
> +        rigidbody = GetComponent<Rigidbody>();
se é obrigatorio, adicionar RequireComponent[typeof(RigidBody)]

2020-11-03 15:17 UTC, PedroRossa commented on Assets/Interactions/Scripts/TranslateToOriginalPositionAfterSeconds.cs
> +        rb = gameObject.GetComponent<Rigidbody>();
se é obrigatório o RigidBody, adicionar RequireComponent[typeof(Rigdbody)]

2020-11-03 15:17 UTC, PedroRossa commented on Assets/Interactions/Scripts/Walk.cs
> +public class Walk : MonoBehaviour
O nome desta classe não está muito intuitivo

2020-11-03 15:17 UTC, PedroRossa commented on Assets/Interactions/Scripts/Walk.cs
> +        rigidbody = gameObject.GetComponent<Rigidbody>();
se é obrigatorio, adicionar RequireComponent[typeof(Rigdbody)]

2020-11-03 15:17 UTC, PedroRossa commented on Assets/UIElements/_Elements/XRUI_Buttons/Scripts/XRUI_3DButtonCollisionDetection.cs
> +            catch (System.Exception) { }
Retornar o erro

2020-11-03 15:17 UTC, PedroRossa commented on Assets/UIElements/_Elements/XRUI_Buttons/Scripts/XRUI_3DButtonSprite.cs
> +        catch (System.NullReferenceException) { }
retornar erro

2020-11-03 15:17 UTC, PedroRossa commented on Assets/UIElements/_Elements/XRUI_Buttons/Scripts/XRUI_3DButtonSprite.cs
> +    public XRUI_3DButtonBase[] othersButtons;
o que são esses outros buttons???

2020-11-03 15:17 UTC, PedroRossa commented on Assets/UIElements/_Elements/XRUI_Feedback/Scripts/XRUI_FeedbackColor.cs
> +    public Color memoryColor;
memorycolor seria a initialcolor?
este nome está um pouco confuso

2020-11-03 17:32 UTC, GMoreira-Tro commented on Assets/UIElements/_Elements/XRUI_Feedback/Scripts/XRUI_FeedbackColor.cs
> +    public Color memoryColor;
Não, é a cor que estava antes de entrar no OnNearEnter, pra voltar a esta cor após sair em OnNearExit

2020-11-03 17:34 UTC, GMoreira-Tro commented on Assets/UIElements/_Elements/XRUI_Buttons/Scripts/XRUI_3DButtonSprite.cs
> +    public XRUI_3DButtonBase[] othersButtons;
Pensando em uma carreira de botões, ao ativar um, os outros seriam desativados. Poder-se-ia mover para XRUI_ButtonBase, talvez, para generalizar

2020-11-03 17:50 UTC, GMoreira-Tro commented on Assets/UIElements/_Elements/XRUI_Buttons/Scripts/XRUI_3DButtonSprite.cs
> +    public XRUI_3DButtonBase[] othersButtons;
Basicamente, seriam os botões que tu quer desativar ao ativar este em questão

2020-11-05 17:55 UTC, GMoreira-Tro commented on Assets/InputManager/DemoScene/ExemploInputHandlers.cs
> +public class ExemploInputHandlers : MonoBehaviour
Feito

2020-11-05 17:55 UTC, GMoreira-Tro commented on Assets/InputManager/DemoScene/ExemploInputHandlers.cs
> +    public InputManager.AxisHandler2D secundaryAxisHandler = null;
Feito

2020-11-05 17:55 UTC, GMoreira-Tro commented on Assets/InputManager/DemoScene/ExemploInputHandlers.cs
> +        secundaryAxisHandler.OnValueChange += PrintSecundaryAxis;
Feito

2020-11-05 17:55 UTC, GMoreira-Tro commented on Assets/InputManager/DemoScene/ExemploInputHandlers.cs
> +    private void PrintSecundaryAxis(XRController controller, Vector2 value)
Feito

2020-11-05 17:56 UTC, GMoreira-Tro commented on Assets/InputManager/Scripts/HandlesSCripts/Axis2DType.cs
> +        Secundary2DAxis
Feito

2020-11-05 17:56 UTC, GMoreira-Tro commented on Assets/Interactions/Scripts/Walk.cs
> +        rigidbody = gameObject.GetComponent<Rigidbody>();
Feito

2020-11-05 17:56 UTC, GMoreira-Tro commented on Assets/UIElements/_Elements/XRUI_Buttons/Scripts/XRUI_3DButtonCollisionDetection.cs
> +            catch (System.Exception) { }
Retornado com Debug.LogError

2020-11-05 17:56 UTC, GMoreira-Tro commented on Assets/UIElements/_Elements/XRUI_Buttons/Scripts/XRUI_3DButtonSprite.cs
> +        catch (System.NullReferenceException) { }
Retornado com Debug.LogError

2020-11-05 17:57 UTC, GMoreira-Tro commented on Assets/UIElements/_Elements/XRUI_Buttons/Scripts/XRUI_3DButtonSprite.cs
> +    public XRUI_3DButtonBase[] othersButtons;
Alterado o nome e colocado na classe base XRUI_3DButtonBase

2020-11-05 17:57 UTC, GMoreira-Tro commented on Assets/UIElements/_Elements/XRUI_Feedback/Scripts/XRUI_FeedbackColor.cs
> +    public Color memoryColor;
Comentado com explicação

2020-11-05 18:16 UTC, PedroRossa requested changes

2020-11-05 18:16 UTC, PedroRossa commented on Assets/Interactions/Scripts/Walk.cs
> +public class Walk : MonoBehaviour
Sugiro um nome composto pra ficar claro na leitura, algo do tipo
RigidBodyWalk ou algo melhor, Diego pode ajudar neste nome!

2020-11-05 18:24 UTC, PedroRossa approved these changes

2020-11-05 18:25 UTC, merged